### slicing in array using numpy

In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30,40,50])

In [4]:
#Slice from index 1 to 4

print (a[1:4])
print(a [:3])
print(a [3:])
print(a [:-1])
print(a [2:3])

[20 30 40]
[10 20 30]
[40 50]
[10 20 30 40]
[30]
